In [ ]:
# Instalar librería Prophet haciendo uso de pip
%pip install prophet

Collecting prophet
  Downloading prophet-1.2.1-py3-none-win_amd64.whl.metadata (3.6 kB)
Collecting cmdstanpy>=1.0.4 (from prophet)
  Downloading cmdstanpy-1.3.0-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: numpy>=1.15.4 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from prophet) (2.3.5)
Requirement already satisfied: matplotlib>=2.0.0 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from prophet) (3.10.7)
Requirement already satisfied: pandas>=1.0.4 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from prophet) (2.3.3)
Collecting holidays<1,>=0.25 (from prophet)
  Downloading holidays-0.85-py3-none-any.whl.metadata (50 kB)
Collecting tqdm>=4.36.1 (from prophet)
  Downloading tqdm-4.67.1-py3-none-any.whl.metadata (57 kB)
Collecting importlib_resources (from prophet)
  Downloading importlib_resources-6.5.2-py3-none-any.whl.metadata (3.9 kB)
Requirement already satisfied: python-dateutil in c:\users\carlos_dubon\appdata\roaming\python\python314\site-packages (from holidays<1,>=0.25->prophet) (2.9.0.post0)
Collecting stanio<2.0.0,>=0.4.0 (from cmdstanpy>=1.0.4->prophet)
  Downloading stanio-0.5.1-py3-none-any.whl.metadata (1.6 kB)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=2.0.0->prophet) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=2.0.0->prophet) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=2.0.0->prophet) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\carlos_dubon\appdata\roaming\python\python314\site-packages (from matplotlib>=2.0.0->prophet) (25.0)
Requirement already satisfied: pillow>=8 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=2.0.0->prophet) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from matplotlib>=2.0.0->prophet) (3.2.5)
Requirement already satisfied: pytz>=2020.1 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\carlos_dubon\appdata\local\programs\python\python314\lib\site-packages (from pandas>=1.0.4->prophet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\carlos_dubon\appdata\roaming\python\python314\site-packages (from python-dateutil->holidays<1,>=0.25->prophet) (1.17.0)
Requirement already satisfied: colorama in c:\users\carlos_dubon\appdata\roaming\python\python314\site-packages (from tqdm>=4.36.1->prophet) (0.4.6)
Downloading prophet-1.2.1-py3-none-win_amd64.whl (12.1 MB)
   ---------------------------------------- 0.0/12.1 MB ? eta -:--:--
    --------------------------------------- 0.3/12.1 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.1 MB 2.2 MB/s eta 0:00:06
   --- ------------------------------------ 1.0/12.1 MB 1.7 MB/s eta 0:00:07
   ----- ---------------------------------- 1.6/12.1 MB 1.9 MB/s eta 0:00:06
   ------ --------------------------------- 1.8/12.1 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 1.8/12.1 MB 2.0 MB/s eta 0:00:06
   ------ --------------------------------- 2.1/12.1 MB 1.4 MB/s eta 0:00:08
   -------- ------------------------------- 2.6/12.1 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.1 MB 1.5 MB/s eta 0:00:07
   -------- ------------------------------- 2.6/12.1 MB 1.5 MB/s eta 0:00:07
   --------- ------------------------------ 2.9/12.1 MB 1.2 MB/s eta 0:00:08
   ---------- ----------------------------- 3.1/12.1 MB 1.3 MB/s eta 0:00:08
   ------------ --------------------------- 3.7/12.1 MB 1.4 MB/s eta 0:00:07
   ------------ --------------------------- 3.9/12.1 MB 1.3 MB/s eta 0:00:07
   -------------- ------------------------- 4.5/12.1 MB 1.4 MB/s eta 0:00:06
   ----------------- ---------------------- 5.2/12.1 MB 1.5 MB/s eta 0:00:05
   ------------------ --------------------- 5.5/12.1 MB 1.6 MB/s eta 0:00:05
   ------------------ --------------------- 5.5/12.1 MB 1.6 MB/s eta 0:00:05
   ------------------- -------------------- 5.8/12.1 MB 1.5 MB/s eta 0:00:05
   --------------------- ------------------ 6.6/12.1 MB 1.5 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ---------------------- ----------------- 6.8/12.1 MB 1.6 MB/s eta 0:00:04
   ----------------------- ---------------- 7.1/12.1 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 7.1/12.1 MB 1.1 MB/s eta 0:00:05
   ----------------------- ---------------- 7.1/12.1 MB 1.1 MB/s eta 0:00:05
   ------------------------ --------------- 7.3/12.1 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.6/12.1 MB 1.1 MB/s eta 0:00:05
   ------------------------- -------------- 7.9/12.1 MB 1.1 MB/s eta 0:00:04
   --------------------------- ------------ 8.4/12.1 MB 1.1 MB/s eta 0:00:04
   ------------------------------ --------- 9.2/12.1 MB 1.2 MB/s eta 0:00:03
   -------------------------------- ------- 10.0/12.1 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.1 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.1 MB 1.3 MB/s eta 0:00:02
   -------------------------------- ------- 10.0/12.1 MB 1.3 MB/s eta 0:00:02
   --------------------------------- ------ 10.2/12.1 MB 1.2 MB/s eta 0:00:02
   --------------------------------- ------ 10.2/12.1 MB 1.2 MB/s eta 0:00:02
   ---------------------------------- ----- 10.5/12.1 MB 1.2 MB/s eta 0:00:02
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/12.1 MB 1.2 MB/s eta 0:00:01
   -------------------------------------- - 11.5/12.1 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.5/12.1 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.5/12.1 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.5/12.1 MB 1.1 MB/s eta 0:00:01
   -------------------------------------- - 11.8/12.1 MB 1.0 MB/s eta 0:00:01
   ---------------------------------------- 12.1/12.1 MB 1.0 MB/s  0:00:11
Downloading holidays-0.85-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ------------------------------- -------- 1.0/1.3 MB 2.0 MB/s eta 0:00:01
   ---------------------------------------- 1.3/1.3 MB 2.0 MB/s  0:00:00
Downloading cmdstanpy-1.3.0-py3-none-any.whl (99 kB)
Downloading stanio-0.5.1-py3-none-any.whl (8.1 kB)
Downloading tqdm-4.67.1-py3-none-any.whl (78 kB)
Downloading importlib_resources-6.5.2-py3-none-any.whl (37 kB)
Installing collected packages: tqdm, stanio, importlib_resources, holidays, cmdstanpy, prophet

   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ---------------------------------------- 0/6 [tqdm]
   ------ --------------------------------- 1/6 [stanio]
   ------------- -------------------------- 2/6 [importlib_resources]
   ------------- -------------------------- 2/6 [importlib_resources]
   ------------- -------------------------- 2/6 [importlib_resources]
   ------------- -------------------------- 2/6 [importlib_resources]
   ------------- -------------------------- 2/6 [importlib_resources]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------- ------------------- 3/6 [holidays]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   -------------------------- ------------- 4/6 [cmdstanpy]
   --------------------------------- ------ 5/6 [prophet]
   --------------------------------- ------ 5/6 [prophet]
   --------------------------------- ------ 5/6 [prophet]
   --------------------------------- ------ 5/6 [prophet]
   --------------------------------- ------ 5/6 [prophet]
   --------------------------------- ------ 5/6 [prophet]
   --------------------------------- ------ 5/6 [prophet]
   ---------------------------------------- 6/6 [prophet]

Successfully installed cmdstanpy-1.3.0 holidays-0.85 importlib_resources-6.5.2 prophet-1.2.1 stanio-0.5.1 tqdm-4.67.1
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from prophet import Prophet

c:\Users\carlos_dubon\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Importing plotly failed. Interactive plots will not work.

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/facebook/prophet/main/examples/example_wp_log_peyton_manning.csv')
df

              ds          y
0     2007-12-10   9.590761
1     2007-12-11   8.519590
2     2007-12-12   8.183677
3     2007-12-13   8.072467
4     2007-12-14   7.893572
...          ...        ...
2900  2016-01-16   7.817223
2901  2016-01-17   9.273878
2902  2016-01-18  10.333775
2903  2016-01-19   9.125871
2904  2016-01-20   8.891374

[2905 rows x 2 columns]

In [ ]:
# Inicializar el modelo Prophet
# m = Prophet(interval_width=0.95)
m = Prophet()

In [24]:
# Entreanar el modelo
m.fit(df)

20:02:39 - cmdstanpy - INFO - Chain [1] start processing
20:02:39 - cmdstanpy - INFO - Chain [1] done processing

In [25]:
# Prerara un DF que recibira la informacion del forescasting
futuro = m.make_future_dataframe(periods=365, include_history=False)
futuro

            ds
0   2016-01-21
1   2016-01-22
2   2016-01-23
3   2016-01-24
4   2016-01-25
..         ...
360 2017-01-15
361 2017-01-16
362 2017-01-17
363 2017-01-18
364 2017-01-19

[365 rows x 1 columns]

In [26]:
proyeccion = m.predict(futuro)
proyeccion

,ds,trend,yhat_lower,yhat_upper,trend_lower,trend_upper,additive_terms,additive_terms_lower,additive_terms_upper,weekly,weekly_lower,weekly_upper,yearly,yearly_lower,yearly_upper,multiplicative_terms,multiplicative_terms_lower,multiplicative_terms_upper,yhat
0,2016-01-21,7.557961,7.606858,9.530703,7.557961,7.557961,0.999898,0.999898,0.999898,-0.072267,-0.072267,-0.072267,1.072165,1.072165,1.072165,0.0,0.0,0.0,8.557859
1,2016-01-22,7.556936,7.571797,9.578712,7.556936,7.556936,1.016898,1.016898,1.016898,-0.069578,-0.069578,-0.069578,1.086476,1.086476,1.086476,0.0,0.0,0.0,8.573834
2,2016-01-23,7.555911,7.442916,9.255853,7.555911,7.555911,0.786614,0.786614,0.786614,-0.311715,-0.311715,-0.311715,1.098329,1.098329,1.098329,0.0,0.0,0.0,8.342524
3,2016-01-24,7.554886,7.761694,9.660913,7.554886,7.554886,1.155626,1.155626,1.155626,0.048296,0.048296,0.048296,1.107329,1.107329,1.107329,0.0,0.0,0.0,8.710511
4,2016-01-25,7.553860,8.068388,9.911056,7.553860,7.553865,1.465350,1.465350,1.465350,0.352285,0.352285,0.352285,1.113066,1.113066,1.113066,0.0,0.0,0.0,9.019211
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,2017-01-15,7.188902,7.138014,9.256029,6.554669,7.820506,1.018064,1.018064,1.018064,0.048296,0.048296,0.048296,0.969768,0.969768,0.969768,0.0,0.0,0.0,8.206966
361,2017-01-16,7.187877,7.360006,9.742218,6.551307,7.822218,1.344084,1.344084,1.344084,0.352285,0.352285,0.352285,0.991799,0.991799,0.991799,0.0,0.0,0.0,8.531961
362,2017-01-17,7.186851,7.178330,9.455595,6.547944,7.823930,1.132527,1.132527,1.132527,0.119640,0.119640,0.119640,1.012887,1.012887,1.012887,0.0,0.0,0.0,8.319378
363,2017-01-18,7.185826,7.045008,9.289815,6.544212,7.825642,0.966167,0.966167,0.966167,-0.066660,-0.066660,-0.066660,1.032828,1.032828,1.032828,0.0,0.0,0.0,8.151994
364,2017-01-19,7.184801,7.045519,9.380116,6.540430,7.827353,0.979109,0.979109,0.979109,-0.072267,-0.072267,-0.072267,1.051377,1.051377,1.051377,0.0,0.0,0.0,8.163910

In [ ]:
# Mostrar solo las columnas relevantes
proyeccion[['ds','yhat','yhat_lower','yhat_upper']]

            ds      yhat  yhat_lower  yhat_upper
0   2016-01-21  8.557859    7.606858    9.530703
1   2016-01-22  8.573834    7.571797    9.578712
2   2016-01-23  8.342524    7.442916    9.255853
3   2016-01-24  8.710511    7.761694    9.660913
4   2016-01-25  9.019211    8.068388    9.911056
..         ...       ...         ...         ...
360 2017-01-15  8.206966    7.138014    9.256029
361 2017-01-16  8.531961    7.360006    9.742218
362 2017-01-17  8.319378    7.178330    9.455595
363 2017-01-18  8.151994    7.045008    9.289815
364 2017-01-19  8.163910    7.045519    9.380116

[365 rows x 4 columns]

In [21]:
# # Prerara un DF que recibira la informacion del forescasting
futuroMensual = m.make_future_dataframe(periods=12, include_history=False, freq='M')
futuroMensual

c:\Users\carlos_dubon\AppData\Local\Programs\Python\Python314\Lib\site-packages\prophet\forecaster.py:1872: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  dates = pd.date_range(

           ds
0  2016-01-31
1  2016-02-29
2  2016-03-31
3  2016-04-30
4  2016-05-31
5  2016-06-30
6  2016-07-31
7  2016-08-31
8  2016-09-30
9  2016-10-31
10 2016-11-30
11 2016-12-31

In [22]:
prediccionmensual = m.predict(futuroMensual)
prediccionmensual[['ds','yhat','yhat_lower','yhat_upper']]

           ds      yhat  yhat_lower  yhat_upper
0  2016-01-31  8.652259    7.973598    9.268959
1  2016-02-29  7.401503    6.772256    7.973301
2  2016-03-31  6.842634    6.214124    7.418530
3  2016-04-30  6.819934    6.199785    7.459666
4  2016-05-31  6.793507    6.182642    7.428224
5  2016-06-30  6.497749    5.849965    7.122502
6  2016-07-31  7.113003    6.506670    7.759213
7  2016-08-31  7.432622    6.780598    8.070103
8  2016-09-30  7.701868    7.084524    8.435760
9  2016-10-31  8.023816    7.322969    8.702940
10 2016-11-30  7.740812    6.969314    8.432619
11 2016-12-31  7.474378    6.744633    8.103808